/**
 * Applica tutte le fix al database Supabase (v2.0)
 * Usa il Personal Access Token (SUPABASE_ADMIN_TOKEN) tramite Management API
 * Se l'API fallisce, genera un file FIX-ALL.SQL per esecuzione manuale
 */
const PROJECT_REF = 'rdqsmfgpbuswzilgbjyr';
const FS = require('fs');
const PATH = require('path');

const ADMIN_TOKEN = process.env.SUPABASE_ADMIN_TOKEN
  || process.env.ADMIN_TOKEN
  || process.env.SUPABASE_TOKEN || '';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
  || process.env.SERVICE_ROLE_KEY
  || process.env.SUPABASE_SERVICE_KEY
  || process.env.VITE_SUPABASE_SERVICE_KEY || '';
const ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || '';
const SUPABASE_URL = process.env.VITE_SUPABASE_URL || 'https://rdqsmfgpbuswzilgbjyr.supabase.co';
const API_BASE = 'https://api.supabase.com/v1';

async function sql(query) {
  const res = await fetch(`${API_BASE}/projects/${PROJECT_REF}/database/query`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${ADMIN_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ query })
  });
  if (!res.ok) {
    const t = await res.text();
    console.error(`  \u274C ${t.slice(0, 150)}`);
    return null;
  }
  try { return JSON.parse(await res.text()); } catch { return await res.text(); }
}

function generateFallbackSql(fixes) {
  let out = '-- ============================================\n' +
    '-- FIX-ALL.SQL \u2014 Generated by apply-fixes.js\n' +
    '-- Esegui in: https://supabase.com/dashboard/project/' + PROJECT_REF + '/sql/new\n' +
    '-- ============================================\n\n';
  for (const f of fixes) {
    out += f + '\n\n';
  }
  return out;
}

function getFixes() {
  return [
    `ALTER TABLE ads ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}';`,
    `ALTER TABLE ads ADD COLUMN IF NOT EXISTS boost_count INT DEFAULT 0;`,
    `ALTER TABLE ads ADD COLUMN IF NOT EXISTS boost_available INT DEFAULT 0;`,
    `ALTER TABLE ads ADD COLUMN IF NOT EXISTS photo_classification TEXT DEFAULT 'safe';`,

    `CREATE TABLE IF NOT EXISTS support_messages (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      user_id UUID,
      email TEXT NOT NULL,
      message TEXT NOT NULL,
      is_read BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;`,
    `DROP POLICY IF EXISTS "Support messages insert" ON support_messages CASCADE;`,
    `CREATE POLICY "Support messages insert" ON support_messages FOR INSERT WITH CHECK (true);`,
    `DROP POLICY IF EXISTS "Support messages select admin" ON support_messages CASCADE;`,
    `CREATE POLICY "Support messages select admin" ON support_messages FOR SELECT USING (auth.uid() IN (
      SELECT id FROM profiles WHERE email IN ('walterzannoni90@outlook.it','walterzannoni90@gmail.com','Lucianopoleselli@icloud.com')
    ));`,

    `CREATE OR REPLACE FUNCTION get_stats()
    RETURNS JSON LANGUAGE plpgsql AS $$
    DECLARE t1 INT; t2 INT; t3 INT; t4 INT; t5 INT;
    BEGIN
      SELECT COUNT(*) INTO t1 FROM ads WHERE is_active = true;
      SELECT COUNT(*) INTO t2 FROM ads WHERE is_premium = true AND is_active = true;
      SELECT COUNT(*) INTO t3 FROM profiles WHERE is_verified = true;
      SELECT COUNT(*) INTO t4 FROM cities;
      SELECT COUNT(*) INTO t5 FROM categories;
      RETURN json_build_object('totalAds',t1,'premiumAds',t2,'verifiedUsers',t3,'citiesAvailable',t4,'categoriesAvailable',t5);
    END; $$;`,

    `CREATE OR REPLACE FUNCTION public.handle_new_user()    RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$    BEGIN      INSERT INTO public.profiles (id, email, name)      VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'''name''', split_part(NEW.email, '''@''', 1)))      ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;      RETURN NEW;    END;$$;`,
    `DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;`,
    `CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();`,
    `UPDATE public.profiles p SET email = u.email FROM auth.users u WHERE p.id = u.id AND (p.email IS NULL OR p.email = '');`,

    `DROP POLICY IF EXISTS "Annunci pubblici" ON ads CASCADE;`,
    `CREATE POLICY "Annunci pubblici" ON ads FOR SELECT USING (is_active = true OR auth.uid() = user_id);`,
    `DROP POLICY IF EXISTS "Propri annunci insert" ON ads CASCADE;`,
    `CREATE POLICY "Propri annunci insert" ON ads FOR INSERT WITH CHECK (auth.uid() = user_id);`,
    `DROP POLICY IF EXISTS "Propri annunci update" ON ads CASCADE;`,
    `CREATE POLICY "Propri annunci update" ON ads FOR UPDATE USING (auth.uid() = user_id);`,
    `DROP POLICY IF EXISTS "Propri annunci delete" ON ads CASCADE;`,
    `CREATE POLICY "Propri annunci delete" ON ads FOR DELETE USING (auth.uid() = user_id);`,

    `CREATE TABLE IF NOT EXISTS city_districts (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      city TEXT REFERENCES cities(name) ON DELETE CASCADE,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      description TEXT DEFAULT '',
      sort_order INT DEFAULT 0,
      UNIQUE(city, slug)
    );`,

    `CREATE TABLE IF NOT EXISTS messages (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      sender_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
      receiver_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
      ad_id UUID REFERENCES ads(id) ON DELETE SET NULL,
      subject TEXT DEFAULT '',
      body TEXT NOT NULL,
      is_read BOOLEAN DEFAULT false,
      is_flagged BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE TABLE IF NOT EXISTS subscription_plans (
      code TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT DEFAULT '',
      price_monthly DECIMAL(10,2) NOT NULL DEFAULT 0,
      highlight_ads INT DEFAULT 0,
      boost_count INT DEFAULT 0,
      verified_badge BOOLEAN DEFAULT false,
      priority_support BOOLEAN DEFAULT false,
      no_ads BOOLEAN DEFAULT false,
      sort_order INT DEFAULT 0
    );`,

    `CREATE TABLE IF NOT EXISTS user_subscriptions (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
      plan_code TEXT REFERENCES subscription_plans(code) ON DELETE SET NULL,
      status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','cancelled','expired','trial')),
      auto_renew BOOLEAN DEFAULT true,
      current_period_start TIMESTAMPTZ DEFAULT NOW(),
      current_period_end TIMESTAMPTZ,
      trial_end TIMESTAMPTZ,
      cancelled_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE TABLE IF NOT EXISTS age_verifications (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','verified','rejected','expired')),
      document_type TEXT DEFAULT '',
      document_image TEXT DEFAULT '',
      selfie_image TEXT DEFAULT '',
      verified_at TIMESTAMPTZ,
      expires_at TIMESTAMPTZ,
      notes TEXT DEFAULT '',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE TABLE IF NOT EXISTS ad_views (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      ad_id UUID REFERENCES ads(id) ON DELETE CASCADE,
      user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
      ip_address TEXT DEFAULT '',
      viewed_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE TABLE IF NOT EXISTS ad_contacts (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      ad_id UUID REFERENCES ads(id) ON DELETE CASCADE,
      contact_type TEXT NOT NULL CHECK (contact_type IN ('phone','whatsapp','telegram','email','message')),
      user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE TABLE IF NOT EXISTS site_settings (
      key TEXT PRIMARY KEY,
      value JSONB DEFAULT '{}',
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );`,

    `CREATE INDEX IF NOT EXISTS idx_messages_receiver ON messages(receiver_id, is_read);`,
    `CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);`,
    `CREATE INDEX IF NOT EXISTS idx_ad_views_ad ON ad_views(ad_id);`,
    `CREATE INDEX IF NOT EXISTS idx_ad_views_date ON ad_views(viewed_at);`,
    `CREATE INDEX IF NOT EXISTS idx_ad_contacts_ad ON ad_contacts(ad_id);`,
    `CREATE INDEX IF NOT EXISTS idx_age_verifications_user ON age_verifications(user_id);`,
    `CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user ON user_subscriptions(user_id);`,
    `CREATE INDEX IF NOT EXISTS idx_city_districts_city ON city_districts(city);`,

    `ALTER TABLE city_districts ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE messages ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE age_verifications ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE ad_views ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE ad_contacts ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;`,

    `DROP POLICY IF EXISTS "City districts pubblici" ON city_districts CASCADE;`,
    `CREATE POLICY "City districts pubblici" ON city_districts FOR SELECT USING (true);`,

    `DROP POLICY IF EXISTS "Messages view" ON messages CASCADE;`,
    `CREATE POLICY "Messages view" ON messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);`,
    `DROP POLICY IF EXISTS "Messages insert" ON messages CASCADE;`,
    `CREATE POLICY "Messages insert" ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);`,

    `DROP POLICY IF EXISTS "Subscriptions view" ON user_subscriptions CASCADE;`,
    `CREATE POLICY "Subscriptions view" ON user_subscriptions FOR SELECT USING (auth.uid() = user_id);`,
    `DROP POLICY IF EXISTS "Subscriptions insert" ON user_subscriptions CASCADE;`,
    `CREATE POLICY "Subscriptions insert" ON user_subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);`,

    `DROP POLICY IF EXISTS "Age verifications view" ON age_verifications CASCADE;`,
    `CREATE POLICY "Age verifications view" ON age_verifications FOR SELECT USING (auth.uid() = user_id);`,
    `DROP POLICY IF EXISTS "Age verifications insert" ON age_verifications CASCADE;`,
    `CREATE POLICY "Age verifications insert" ON age_verifications FOR INSERT WITH CHECK (auth.uid() = user_id);`,

    `DROP POLICY IF EXISTS "Ad views insert" ON ad_views CASCADE;`,
    `CREATE POLICY "Ad views insert" ON ad_views FOR INSERT WITH CHECK (auth.uid() = user_id);`,

    `DROP POLICY IF EXISTS "Site settings pubblici" ON site_settings CASCADE;`,
    `CREATE POLICY "Site settings pubblici" ON site_settings FOR SELECT USING (true);`,

    `INSERT INTO city_districts (city, name, slug, description, sort_order) VALUES
      ('Napoli','Centro Storico','centro-storico','Quartieri Spagnoli, Piazza del Plebiscito, Toledo',1),
      ('Napoli','Vomero','vomero','Zona collinare, alta Napoli',2),
      ('Napoli','Chiaia','chiaia','Lungomare, zona chic, piazza dei Martiri',3),
      ('Napoli','Fuorigrotta','fuorigrotta','Zona ovest, Stadio Maradona, Mostra',4),
      ('Napoli','Posillipo','posillipo','Zona residenziale, panoramica',5),
      ('Napoli','Arenaccia','arenaccia','Zona stazione, centro direzionale',6),
      ('Napoli','Bagnoli','bagnoli','Zona flegrea, lungomare',7),
      ('Napoli','Scampia','scampia','Zona nord',8),
      ('Roma','Centro Storico','centro-storico','Colosseo, Trastevere, Pantheon',1),
      ('Roma','EUR','eur','Zona affari, architettura moderna',2),
      ('Roma','Parioli','parioli','Zona residenziale elegante',3),
      ('Roma','San Giovanni','san-giovanni','Zona popolare centrale',4),
      ('Milano','Centro','centro','Duomo, Brera, fashion district',1),
      ('Milano','Navigli','navigli','Zona movida, canali',2),
      ('Milano','Porta Nuova','porta-nuova','Business district, grattacieli',3),
      ('Milano','Bicocca','bicocca','Zona universitaria',4)
    ON CONFLICT (city, slug) DO NOTHING;`,

    `INSERT INTO subscription_plans (code, name, description, price_monthly, highlight_ads, boost_count, verified_badge, priority_support, no_ads, sort_order) VALUES
      ('free', 'Gratis', 'Account base gratuito', 0, 0, 0, false, false, false, 1),
      ('plus', 'Plus', 'Abbonamento premium con vantaggi esclusivi', 14.99, 5, 10, true, true, false, 2),
      ('vip', 'VIP', 'Esperienza completa senza limiti', 29.99, 20, 30, true, true, true, 3)
    ON CONFLICT (code) DO NOTHING;`
  ];
}

async function main() {
  console.log('\n\ud83d\ude80 Avvio fix database (v2.0)...\n');

  if (!ADMIN_TOKEN) {
    console.log('\u274C SERVIREBBE SUPABASE_ADMIN_TOKEN per fix automatiche.');
    console.log('');
    console.log('\ud83d\udccc Per fixare TU STESSO il database:');
    console.log('  1. Vai su https://supabase.com/dashboard/project/' + PROJECT_REF + '/sql/new');
    console.log('  2. Incolla il contenuto di supabase-schema.sql');
    console.log('  3. Esegui');
    console.log('');
    console.log('\ud83d\udccc Aggiungi questi secret a GitHub:');
    console.log('  - SUPABASE_ADMIN_TOKEN (Personal Access Token sbp_...)');
    console.log('  - SUPABASE_SERVICE_ROLE_KEY (dal dashboard Supabase)');
    console.log('');
    console.log('   Oppure alternativamente:');
    console.log('  - Vai su https://supabase.com/dashboard/account/tokens');
    console.log('  - Genera un nuovo token (es. "github-actions")');
    console.log('  - Aggiungilo come secret SUPABASE_ADMIN_TOKEN su GitHub\n');
    return;
  }

  console.log('\u2705 Admin Token trovato! Applico fix...\n');

  const test = await sql('SELECT 1 AS test');
  if (!test) {
    console.log('\u274C Impossibile connettersi alla Management API. Token non valido?\n');
    const fixes = getFixes();
    const fallbackPath = PATH.join(__dirname, 'FIX-ALL.SQL');
    FS.writeFileSync(fallbackPath, generateFallbackSql(fixes));
    console.log('\ud83d\udccc File ' + fallbackPath + ' generato per esecuzione manuale.\n');
    console.log('   Incolla il contenuto nel SQL Editor di Supabase.\n');
    return;
  }
  console.log('\u2705 Connessione a Supabase Management API riuscita!\n');

  const fixes = getFixes();
  let allOk = true;

  for (let i = 0; i < fixes.length; i++) {
    process.stdout.write(`  [${i + 1}/${fixes.length}] Eseguendo... `);
    const r = await sql(fixes[i]);
    console.log(r !== null ? '\u2705' : '\u26A0\uFE0F  fallita (forse gi\u00e0 applicata)');
    if (r === null) allOk = false;
    await new Promise(r => setTimeout(r, 200));
  }

  if (allOk) {
    console.log('\n\u2705 Tutte le fix v2.0 sono state applicate con successo!\n');
  } else {
    console.log('\n\u26A0\uFE0F  Alcune fix non sono state applicate automaticamente.\n');
    const fallbackPath = PATH.join(__dirname, 'FIX-ALL.SQL');
    FS.writeFileSync(fallbackPath, generateFallbackSql(fixes));
    console.log('\ud83d\udccc File ' + fallbackPath + ' generato per completare manualmente.\n');
    console.log('   Incolla il contenuto nel SQL Editor di Supabase.\n');
  }
}

main().catch(console.error);
