#!/bin/bash
# ===============================================================
# MASSIVE BACKLINK LIST — OLTRE 500 DIRECTORY + SOCIAL + FORUM
# ===============================================================
# APRI OGNI URL NEL BROWSER E REGISTRA/INVIA IL SITO
#
# DATI DA USARE:
#   Sito: https://incontridibakeka.com
#   Titolo: Incontri di Bakeka
#   Descrizione: Annunci di incontri verificati in Italia. Profili autentici, connessioni reali.
#   Categoria: Incontri, Dating, Annunci, Servizi Online
#   Email: walterzannoni90@outlook.it
# ===============================================================

SITE="https://incontridibakeka.com"
TITLE="Incontri di Bakeka"
DESC="Annunci di incontri verificati in Italia. Profili autentici, connessioni reali. Il sito leader per incontri a Roma, Milano, Napoli, Torino."
EMAIL="walterzannoni90@outlook.it"

echo "============================================================"
echo "  OLTRE 500 FONTI PER BACKLINK"
echo "  Apri ogni link, registrati (se serve) e invia il sito"
echo "============================================================"
echo ""

# =====================
# TOP DIRECTORY (DA 60+)
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  TOP DIRECTORY (DA 60+)"
echo "════════════════════════════════════════════════════════════"
TOP=(
  "https://www.crunchbase.com"
  "https://www.trustpilot.com"
  "https://angel.co"
  "https://www.tomtom.com"
  "https://www.g2.com"
  "https://www.linkedin.com/company"
  "https://www.blogarama.com"
  "https://somuch.com"
  "https://www.ontoplist.com"
  "https://www.exactseek.com"
  "https://www.highrankdirectory.com"
  "https://www.marketinginternetdirectory.com"
  "https://www.freeprwebdirectory.com"
  "https://www.usawebsitesdirectory.com"
  "https://www.prolinkdirectory.com"
  "https://www.hitwebdirectory.com"
  "https://www.gmawebdirectory.com"
  "https://www.siteswebdirectory.com"
  "https://www.dizila.com"
  "https://www.traveltourismdirectory.com"
  "https://www.allstatesusadirectory.com"
  "https://www.informationcrawler.com"
  "https://www.qualityinternetdirectory.com"
  "https://www.familydir.com"
  "https://www.marketingwebdirectory.com"
  "https://www.webdirectoryhealth.com"
  "https://homepageseek.com"
  "https://www.onemilliondirectory.com"
  "https://viesearch.com"
  "https://aweblist.org"
  "https://www.9sites.net"
  "https://www.traveltourismdirectory.net"
  "https://www.linkdirectorylistings.org"
  "https://www.sitepromotiondirectory.com"
  "https://www.skoobe.biz"
  "https://www.submit.biz"
  "https://www.morefunz.com"
  "https://www.txtlinks.com"
  "https://www.piseries.com"
  "https://weboworld.com"
  "https://www.directory-link.com"
)
for url in "${TOP[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# DIRECTORY ITALIANE
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  DIRECTORY ITALIANE"
echo "════════════════════════════════════════════════════════════"
ITALIANE=(
  "https://www.elinko.it/inserisci-sito/"
  "https://www.paginebianche.it/inserisci-attivita"
  "https://www.paginegialle.it/inserisci-scheda"
  "https://siti.virgilio.it/aggiungi-sito.html"
  "https://www.hotfrog.it/aggiungere-azienda"
  "https://www.nuovosito.com/inserisci-sito.asp"
  "https://www.freeonline.org/submit.php"
  "https://www.gratis.it/aj/aggiungi.php"
  "https://www.segnala.it/aggiungi-sito/"
  "https://www.mrlink.it/contatti/"
  "https://www.aziende-italiane-siti.it/inserisci-sito/"
  "https://www.tuttitalia.it/segnala-sito/"
  "https://www.initalia.it/inserisci-sito/"
  "https://www.sitiwebitalia.net/aggiungi-sito/"
  "https://www.webitalia.net/segnala/"
  "https://www.italiaindice.it/inserisci-sito/"
  "https://www.segnalo.it/aggiungi-sito/"
  "https://www.katalogi.it/aggiungi.php"
  "https://www.topdir.it/inserisci-sito/"
  "https://www.prontoweb.it/aggiungi-sito"
  "https://www.sitiweb24.it/inserisci-sito/"
  "https://www.paginesiti.it/aggiungi-sito"
  "https://www.mondo-web.it/aggiungi-sito/"
  "https://www.diritalia.it/inserisci/"
  "https://www.annunci-subito.it/inserisci-annuncio/"
  "https://www.sitiamici.net/aggiungi-sito/"
  "https://www.italiandir.it/submit.php"
  "https://www.inrete.it/inserisci-sito/"
  "https://www.segnalazioni.com/aggiungi-sito/"
  "https://www.segnala.org/"
  "https://www.bookmarky.it/"
  "https://www.diggitalia.it/"
  "https://www.andreagabrielli.it/web-directory/"
  "https://www.segnala.org/aggiungi-sito/"
  "https://www.misterimprese.it"
  "https://www.aziendegratis.it"
  "https://www.4yougratis.it"
  "https://www.dirhello.com"
  "https://www.italymedia.it"
  "https://www.italiasearch.it"
  "https://www.babulaweb.com"
  "https://www.oneonline.it/motorone"
  "https://www.directory-italia.com"
)
for url in "${ITALIANE[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# MEDIUM DIRECTORY (DA 40-59)
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  MEDIUM DIRECTORY (DA 40-59)"
echo "════════════════════════════════════════════════════════════"
MEDIUM=(
  "https://www.exportersindia.com"
  "https://www.prsync.com"
  "https://www.storeboard.com"
  "https://www.reviewcentre.com"
  "https://www.fundoodata.com"
  "https://www.indiacom.com"
  "https://www.tupalo.com"
  "https://www.fyple.com"
  "https://www.place123.net"
  "https://www.activdirectory.net"
  "https://www.promotebusinessdirectory.com"
  "https://www.directory.com.au"
  "https://www.ukinternetdirectory.net"
  "https://www.britainbusinessdirectory.com"
  "https://www.gainweb.org"
  "https://www.info-listings.com"
  "https://www.craigslistdir.org"
  "https://www.quicklinks.net"
  "https://www.canadawebdir.com"
  "https://www.submissionwebdirectory.com"
  "https://www.linksgiving.com"
  "https://www.abstractdirectory.net"
  "https://www.one-sublime-directory.com"
  "https://www.ellysdirectory.com"
  "https://www.directoryworld.net"
  "https://www.upsdirectory.com"
  "https://www.eindiabusiness.com"
  "https://www.pegasusdirectory.com"
  "https://www.directory6.org"
  "https://www.ask-directory.com"
  "https://www.indiacatalog.com"
  "https://www.linkorado.com"
  "https://www.netinsert.com"
  "https://www.localbiznetwork.com"
  "https://www.exampledir.com"
  "https://www.domainnamesseo.com"
  "https://www.addgoodsites.com"
  "https://www.ezistreet.com"
  "https://www.newwebdirectory.com"
  "https://www.jasminedirectory.com"
  "https://www.submitexpress.com"
  "https://www.directoryvault.com"
  "https://www.buyersindex.com"
  "https://www.cipinet.com"
  "https://www.10directory.com"
  "https://www.webwiki.co.uk"
  "https://www.freeseolink.org"
  "https://www.onecooldir.com"
  "https://www.searchdomainhere.com"
  "https://www.dirjournal.info"
  "https://www.beegdirectory.com"
  "https://www.secure.linkcentre.com"
  "https://www.sitesondisplay.com"
  "https://www.blackgreendirectory.com"
  "https://www.websquash.com"
  "https://www.expansiondirectory.com"
  "https://www.target-directory.com"
  "https://www.acewebdirectory.com"
  "https://www.groovy-directory.com"
  "https://www.deepbluedirectory.com"
  "https://www.bluebook-directory.com"
  "https://www.greenydirectory.com"
  "https://www.bluesparkledirectory.com"
  "https://www.fire-directory.com"
  "https://www.angelsdirectory.com"
  "https://www.daduru.com"
  "https://www.bananadirectories.com"
  "https://www.poordirectory.com"
  "https://www.justlink.org"
)
for url in "${MEDIUM[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# BUSINESS/LOCAL LISTINGS
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  BUSINESS & LOCAL LISTINGS"
echo "════════════════════════════════════════════════════════════"
LOCAL=(
  "https://www.google.com/business/go/"
  "https://www.bing.com/webmasters/"
  "https://www.yelp.com"
  "https://www.yellowpages.com"
  "https://www.superpages.com"
  "https://www.citysearch.com"
  "https://www.merchantcircle.com"
  "https://www.hotfrog.com"
  "https://www.manta.com"
  "https://www.cylex.us.com"
  "https://www.judyrecords.com"
  "https://www.kompass.com"
  "https://www.trademap.org"
  "https://www.europages.com"
  "https://www.app.findthecompany.com"
  "https://www.ezlocal.com"
  "https://www.fyple.com"
  "https://www.ibegin.com"
  "https://www.local.com"
  "https://www.n49.com"
  "https://www.opendi.com"
  "https://www.owlstown.com"
  "https://www.showmelocal.com"
  "https://www.tupalo.com"
  "https://www.usbusinesslistings.net"
  "https://www.wikibizpedia.com"
  "https://www.yalwa.com"
  "https://www.yellowassistance.com"
  "https://www.yellowpage-city.com"
  "https://www.4elitebusinesslistings.com"
  "https://www.abc-directory.com"
  "https://www.allbusinesslistings.com"
  "https://www.brownbook.net"
  "https://www.business-listings.net"
  "https://www.businessfinder.net"
  "https://www.calibizlistings.com"
  "https://www.classifiedads.com"
  "https://www.clickcity.com"
  "https://www.companycheck.co.uk"
  "https://www.cylex.de"
  "https://www.desiwale.com"
  "https://www.findthecompany.com"
  "https://www.freebusinessdirectory.net"
  "https://www.getfave.com"
  "https://www.globalb2bcontacts.com"
  "https://www.infobel.com"
  "https://www.insiderpages.com"
  "https://www.kellysearch.com"
  "https://www.librarytechnology.org"
  "https://www.listingall.com"
  "https://www.localstore.com"
  "https://www.mysitemap.net"
  "https://www.nationalbusinessregister.com"
  "https://www.nicebusinessdirectory.com"
  "https://www.place789.com"
  "https://www.smartpage.com"
  "https://www.startlocal.com.au"
  "https://www.topbusinesslistings.com"
  "https://www.truelocal.com.au"
  "https://www.uae-business-directory.com"
  "https://www.usdirectory.com"
  "https://www.webdirectory.com"
  "https://www.wherezato.com"
  "https://www.worldwebdirectory.com"
  "https://www.yellowpages.com.au"
  "https://www.yenisehirwiki.com"
)
for url in "${LOCAL[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# SOCIAL BOOKMARKING
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  SOCIAL BOOKMARKING"
echo "════════════════════════════════════════════════════════════"
BOOKMARKS=(
  "https://www.digg.com"
  "https://www.delicious.com"
  "https://www.stumbleupon.com"
  "https://www.reddit.com"
  "https://www.scoop.it"
  "https://www.bibsonomy.org"
  "https://www.diigo.com"
  "https://www.folkd.com"
  "https://www.connotea.org"
  "https://www.mix.com"
  "https://www.pinterest.com"
  "https://www.plurk.com"
  "https://www.evernote.com"
  "https://www.instapaper.com"
  "https://www.meneame.net"
  "https://www.pearltrees.com"
  "https://www.sharethis.com"
  "https://www.slashdot.org"
  "https://www.socialbookmarking.net"
  "https://www.symbaloo.com"
  "https://www.tripoto.com"
  "https://www.wikio.com"
  "https://www.connotea.org"
  "https://www.efloral.com"
  "https://www.newsvine.com"
  "https://www.technorati.com"
  "https://www.fark.com"
  "https://www.tipd.com"
  "https://www.blinklist.com"
  "https://www.blogmarks.net"
  "https://www.bobsguide.com"
  "https://www.businessmarketingone.com"
  "https://www.citeulike.org"
  "https://www.connotea.org"
  "https://www.dzone.com"
  "https://www.favoora.com"
  "https://www.furl.net"
  "https://www.google.com/bookmarks"
  "https://www.hellotxt.com"
  "https://www.icerocket.com"
  "https://www.imagesocket.com"
  "https://www.jumptags.com"
  "https://www.kirtsy.com"
  "https://www.linkagogo.com"
  "https://www.livejournal.com"
  "https://www.mister-wong.com"
  "https://www.myhq.com"
  "https://www.netvouz.com"
  "https://www.onlywire.com"
  "https://www.propeller.com"
  "https://www.rawsugar.com"
  "https://www.recibo.com"
  "https://www.shoutwire.com"
  "https://www.simpy.com"
  "https://www.socialposter.com"
  "https://www.sphere.com"
  "https://www.startaid.com"
  "https://www.surfnx.com"
  "https://www.sys-con.com"
  "https://www.tailsweep.com"
  "https://www.thingslabs.com"
  "https://www.topix.net"
  "https://www.topsite.com"
  "https://www.tradepals.com"
  "https://www.uplood.com"
  "https://www.urldossier.com"
  "https://www.whitelinks.com"
  "https://www.wikidot.com"
  "https://www.wikio.com"
  "https://www.xmarks.com"
)
for url in "${BOOKMARKS[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# FORUM ITALIANI
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  FORUM ITALIANI (crea profilo + firma con link)"
echo "════════════════════════════════════════════════════════════"
FORUMS=(
  "https://www.forumfree.net/?act=register"
  "https://www.forumcommunity.net/?act=register"
  "https://forum.tuttoandroid.net/register.php"
  "https://forum.html.it/forum/register.php"
  "https://forum.pcfaster.it/member.php?action=register"
  "https://forum.incontri.forumfree.it"
  "https://forum.donna.it/member.php?action=register"
  "https://forum.altervista.org/member.php?action=register"
  "https://forum.meteonetwork.it/register.php"
  "https://forum.hwupgrade.it/register.php"
  "https://forum.iphoneitalia.com/register.php"
  "https://forum.teamdigitale.it"
  "https://forum.softwareliberamente.org"
  "https://forum.chat-italia.it"
  "https://forum.pianetadonna.it"
  "https://forum.amoremio.it"
  "https://forum.cuorecuori.it"
  "https://forum.vampireforum.net"
  "https://forum.italianidating.it"
  "https://forum.loveandromance.it"
  "https://forum.solocoseitaliane.it"
  "https://forum.amicizie-incontri.it"
  "https://forum.donnedating.it"
  "https://forum.uominiedonne.it"
  "https://forum.romantico.it"
  "https://forum.appuntamenti-online.it"
  "https://forum.animasingola.it"
  "https://forum.amoremio.org"
  "https://forum.amicizieincontri.it"
  "https://forum.incontritra.it"
  "https://forum.datingadvisor.it"
  "https://forum.italiadating.it"
  "https://forum.incontri-sicuri.it"
  "https://forum.chatamici.it"
  "https://forum.gruppiamici.it"
  "https://forum.partnerincontri.it"
  "https://forum.romadating.it"
  "https://forum.milanodating.it"
  "https://forum.napolidating.it"
  "https://forum.torinodating.it"
)
for url in "${FORUMS[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# ARTICLE PLATFORMS
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  ARTICLE PLATFORMS (pubblichi articoli con link)"
echo "════════════════════════════════════════════════════════════"
ARTICLES=(
  "https://medium.com"
  "https://www.linkedin.com/pulse/"
  "https://www.quora.com"
  "https://www.articlesbase.com"
  "https://ezinearticles.com"
  "https://www.goarticles.com"
  "https://www.articlealley.com"
  "https://www.articlecity.com"
  "https://www.articledashboard.com"
  "https://seekingalpha.com"
  "https://www.selfgrowth.com"
  "https://www.buzzle.com"
  "https://www.articlebiz.com"
  "https://www.ideamarketers.com"
  "https://www.isnare.com"
  "https://www.constant-content.com"
  "https://www.article-hub.com"
  "https://www.articlecrux.com"
  "https://www.articlesfactory.com"
  "https://www.articlesnatch.com"
  "https://www.articlestone.com"
  "https://www.articleweb55.com"
  "https://www.articlesmaker.com"
  "https://www.articleentry.com"
  "https://www.free-articles-zone.com"
  "https://www.articlegrow.com"
  "https://www.article-directory.net"
  "https://www.articlenorth.com"
  "https://www.article-idea.com"
  "https://www.bestarticledirectory.com"
  "https://www.submityourarticle.com"
  "https://www.pubarticles.com"
  "https://www.articlesphere.com"
  "https://www.articlevibe.com"
  "https://www.constantcontent.com"
)
for url in "${ARTICLES[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# CLASSIFIED ADS ITALIA
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  ANNUNCI GRATUITI ITALIA"
echo "════════════════════════════════════════════════════════════"
CLASSIFIEDS=(
  "https://www.subito.it"
  "https://www.bakeka.it"
  "https://www.annunci69.it"
  "https://www.incontritop.it"
  "https://www.anunciositalia.com"
  "https://www.vendo.it"
  "https://www.kijiji.it"
  "https://www.mercatinomusicale.com"
  "https://www.cartasi.it"
  "https://www.trovit.it"
  "https://www.annuncisubito.com"
  "https://www.wannonce.com"
  "https://www.shoppingads.it"
  "https://www.pubblinet.com"
  "https://www.zerocinquanta.com"
  "https://www.annunci.it"
  "https://www.secondamano.it"
  "https://www.inet.it"
  "https://www.bakekaonline.it"
  "https://www.annuncinstantly.it"
  "https://www.freeadsitalia.com"
  "https://www.topannonci.it"
  "https://www.inserzionisti.it"
  "https://www.pagineannunci.it"
  "https://www.tutti-annunci.it"
  "https://www.trovainserzioni.it"
  "https://www.portale-annunci.it"
  "https://www.meglioannunci.it"
  "https://www.annunciwebitalia.it"
  "https://www.italia-annunci.it"
  "https://www.incontriannunci.it"
  "https://www.datingannunci.it"
  "https://www.incontrisubito.it"
  "https://www.annuncidating.it"
  "https://www.donnedating.it"
)
for url in "${CLASSIFIEDS[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# SOCIAL PLATFORMS
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  SOCIAL PLATFORMS (crea profilo, link in bio)"
echo "════════════════════════════════════════════════════════════"
SOCIAL=(
  "https://www.instagram.com"
  "https://www.tiktok.com"
  "https://www.facebook.com/pages/create"
  "https://www.x.com"
  "https://www.linkedin.com/company"
  "https://www.pinterest.it"
  "https://www.youtube.com"
  "https://www.reddit.com"
  "https://t.me"
  "https://www.whatsapp.com"
  "https://www.snapchat.com"
  "https://www.twitch.tv"
  "https://www.tumblr.com"
  "https://www.flickr.com"
  "https://www.myspace.com"
  "https://www.behance.net"
  "https://www.dribbble.com"
  "https://www.vimeo.com"
  "https://www.soundcloud.com"
  "https://www.medium.com"
  "https://www.quora.com"
  "https://www.slideshare.net"
  "https://www.issuu.com"
  "https://www.scribd.com"
  "https://www.academia.edu"
  "https://www.wattpad.com"
  "https://www.deviantart.com"
  "https://www.about.me"
  "https://www.flipboard.com"
  "https://www.mixcloud.com"
  "https://www.periscope.tv"
  "https://www.storify.com"
  "https://www.threads.net"
  "https://www.bluesky.com"
  "https://www.mastodon.social"
)
for url in "${SOCIAL[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# DIRECTORIES AGGIUNTIVE (DA 20-39)
# =====================
echo "════════════════════════════════════════════════════════════"
echo "  ALTRE DIRECTORY (DA 20-39) — 200+ siti"
echo "════════════════════════════════════════════════════════════"
OTHER=(
  "https://www.411freedirectory.com"
  "https://www.postfreedirectory.com"
  "https://www.digabusiness.com"
  "https://www.advancedseodirectory.com"
  "https://www.bahiacar.com"
  "https://www.dentons.net"
  "https://www.bing-directory.com"
  "https://madewithvuejs.com"
  "https://www.bestbuydir.com"
  "https://smartseolink.org"
  "https://canadawebdir.com"
  "https://huludirectory.com"
  "https://craigslistdirectory.net"
  "https://pr8directory.com"
  "https://reddit-directory.com"
  "https://www.gtspauae.com"
  "https://sizzlingdirectory.com"
  "https://submityourlink.com.ar"
  "https://busybits.com"
  "https://www.247webdirectory.com"
  "https://fwebdirectory.com"
  "https://www.backpagedir.com"
  "https://executivedirectory.com.ar"
  "https://www.alabamaindex.com"
  "https://businessconnect.directory"
  "https://www.afunnydir.com"
  "https://bidsyndicate.com.ar"
  "https://www.digabusiness.com"
  "https://gtspauae.com"
  "https://www.theseobacklink.com"
  "https://www.seooptimizationdirectory.com"
  "https://www.bluebook-directory.com"
  "https://www.aurora-directory.com"
  "https://www.bedirectory.com"
  "https://www.blackdirectory.com"
  "https://www.businesswebmarks.com"
  "https://www.canadianwebdirectory.com"
  "https://www.castlewebdirectory.com"
  "https://www.cleangreendirectory.com"
  "https://www.coolwebdirectory.com"
  "https://www.crystalwebdirectory.com"
  "https://www.directorycar.com"
  "https://www.directoryfield.com"
  "https://www.directoryfaves.com"
  "https://www.directorypods.com"
  "https://www.directorytree.com"
  "https://www.dockerdirectory.com"
  "https://www.dragonwebdirectory.com"
  "https://www.egodirectory.com"
  "https://www.expressdirectory.com"
  "https://www.fastdirectorylistings.com"
  "https://www.free-ads-directory.com"
  "https://www.free-directory-submit.com"
  "https://www.freewebdirectory.com"
  "https://www.freewebsubmission.com"
  "https://www.gemwebdirectory.com"
  "https://www.globaldirectoryspot.com"
  "https://www.goldwebdirectory.com"
  "https://www.goodwebdirectory.com"
  "https://www.greatwebdirectory.com"
  "https://www.hexadirectory.com"
  "https://www.highqualitywebdirectory.com"
  "https://www.hotweburls.com"
  "https://www.idahoindex.com"
  "https://www.infradirectory.com"
  "https://www.jewelwebdirectory.com"
  "https://www.justdirectory.org"
  "https://www.khersonrent.com"
  "https://www.kingsdirectory.com"
  "https://www.legacydirectory.com"
  "https://www.linkshere.com.ar"
  "https://www.litetopia.com"
  "https://www.mediafiredirectlink.com"
  "https://www.medicalhealthdirectory.net"
  "https://www.medicalhealthsites.com"
  "https://www.medirectory.com"
  "https://www.moonsunfavor.com"
  "https://www.mybusinesslisting.net"
  "https://www.mydannyseo.com"
  "https://www.mywebdirectory.com.ar"
  "https://www.nationdirectory.info"
  "https://www.neobacklinks.net"
  "https://www.newfreedirectory.com.ar"
  "https://www.nowshenzhen.com"
  "https://www.oceandirectory.com"
  "https://www.orcca.org"
  "https://www.ourdirectory.info"
  "https://www.podirectory.com"
  "https://www.poec.neobacklinks.net"
  "https://www.projectcollabmanila.com"
  "https://www.qualitydirectorylistings.com"
  "https://www.rankdirectory.com"
  "https://www.royallinkup.com"
  "https://www.searchcandy.com"
  "https://www.searchit.com"
  "https://www.serviceprofessionalsnetwork.com"
  "https://www.showmelocal.com"
  "https://www.silverwebdirectory.com"
  "https://www.simpledirectory.com.ar"
  "https://www.sitemapdirectory.com"
  "https://www.sonicrun.com"
  "https://www.stansmithshoes.org"
  "https://www.sublimedir.net"
  "https://www.submitindustry.com"
  "https://www.supertools.therundown.com"
  "https://www.tagshub.com"
  "https://www.targetsviews.com"
  "https://www.textlinkdirectory.com"
  "https://www.thedirectory.com.ar"
  "https://www.thehillel.org"
  "https://www.theseoking.com"
  "https://www.thunderdirectory.com"
  "https://www.topbusinesslistings.com"
  "https://www.topsitio.com"
  "https://www.unionofdirectories.com"
  "https://www.uniquedirectory.com"
  "https://www.usalistingdirectory.com"
  "https://www.vaultdirectory.com"
  "https://www.viewfreeads.com"
  "https://www.vine8.net"
  "https://www.vipdirectory.com.ar"
  "https://www.web-designers-directory.net"
  "https://www.webdirectory.co.in"
  "https://www.webdirectoryhealth.com"
  "https://www.webguide.com"
  "https://www.webguiding.net"
  "https://www.webhostindustry.com"
  "https://www.websitehostingdirectory.com"
  "https://www.websitelist.com.ar"
  "https://www.welcomelinks.info"
  "https://www.whatsonweb.com"
  "https://www.wlddirectory.com"
  "https://www.worldweb-directory.com"
  "https://www.wowdirectory.com"
  "https://www.w3directory.com"
  "https://www.yourwebdirectory.com"
  "https://www.zendirectory.com.ar"
  "https://www.zendirectory.neobacklinks.net"
  "https://www.cawausa.neobacklinks.net"
  "https://www.652186.neobacklinks.net"
  "https://www.coastradar.info"
  "https://www.coastradar.neobacklinks.net"
  "https://www.fozzeyandvanc.com"
  "https://www.gowwwlist.com"
  "https://www.biz15.co.in"
  "https://www.alive-directory.com"
  "https://www.acedirectory.org"
  "https://www.bizz-directory.com"
  "https://www.blpdirectory.info"
  "https://www.brownedgedirectory.com"
  "https://www.caida.eu"
  "https://www.direct-directory.com"
  "https://www.dirjournal.info"
  "https://www.directoryfree.com"
  "https://www.directorynode.com"
  "https://www.evolvingcritic.com"
  "https://www.fivestarsautopawn.com"
  "https://www.fivestarscenter.com"
  "https://www.fivestarsclothing.com"
  "https://www.findingourway.net"
  "https://www.freetoprankdirectory.com"
  "https://www.fruity-directory.com"
  "https://www.gardendirectory.com.ar"
  "https://www.godirectory.org"
  "https://www.goaflam.net"
  "https://www.goaflam.sunet"
  "https://www.inyectronicawc.com"
  "https://www.link-man.org"
  "https://www.nytimes-seo.com"
  "https://www.powerdirectory.com.ar"
  "https://www.seocopilot.com"
  "https://www.sergiuungureanu.com"
  "https://www.seekwebsites.innovasysindia.com"
  "https://www.websitesindex.medicalbillinglogic.com"
  "https://www.abicloud.org"
  "https://www.alivelinks.org"
  "https://www.alexa.com.ar"
  "https://www.anaximanderdirectory.com"
  "https://www.craigslistdir.org"
  "https://www.dmoztools.net"
  "https://www.dmoz.ebmdattorneys.com"
  "https://www.exactseek.com"
  "https://www.findtoptopics.com"
  "https://www.freeinternetwebdirectory.com"
  "https://www.freewebsubmission.com"
  "https://www.freeprwebdirectory.com"
  "https://www.globalsubmitdirectory.com"
  "https://www.gtspauae.com"
  "https://www.homepageseek.com"
  "https://www.idahoindex.com"
  "https://www.indusdirectory.com"
  "https://www.interesting-dir.com"
  "https://www.jayde.com"
  "https://www.lemon-directory.com"
  "https://www.livewebmarks.com"
  "https://www.listinedirectory.com"
  "https://www.maharashtradirectory.com"
  "https://www.morefunz.com"
  "https://www.midgetsexgalleries.com"
  "https://www.nationaldirectory.com"
  "https://www.ninjadirectory.com"
  "https://www.onlinedir.net"
  "https://www.optimaldirectory.com"
  "https://www.perfectwebdirectory.com"
  "https://www.platinumdirectorylistings.com"
  "https://www.promotebusinessdirectory.com"
  "https://www.quickprwebdirectory.com"
  "https://www.realdirectorylistings.com"
  "https://www.seocopilot.com"
  "https://www.submissionwebdirectory.com"
  "https://www.submit-directory.com"
  "https://www.submitlinkdirectory.com"
  "https://www.sunshinedirectory.com"
  "https://www.traveltourismdirectory.net"
  "https://www.topwebdirectorylistings.com"
  "https://www.uriage.com"
  "https://www.webcitydirectory.com"
  "https://www.webfreehostingdirectory.com"
  "https://www.webhostingdirectory.com"
  "https://www.webmasterdirectory.com"
  "https://www.websitesubmitdirectory.com"
  "https://www.webworlddirectory.com"
  "https://www.webxdirectory.com"
  "https://www.worldwebdirectory.com"
  "https://www.wowdirectory.com"
  "https://www.yoururl.com"
  "https://www.yourdashboard.net"
)
for url in "${OTHER[@]}"; do
  echo "  ➤ $url"
done
echo ""

# =====================
# STATS
# =====================
TOTAL=$(( ${#TOP[@]} + ${#ITALIANE[@]} + ${#MEDIUM[@]} + ${#LOCAL[@]} + ${#BOOKMARKS[@]} + ${#FORUMS[@]} + ${#ARTICLES[@]} + ${#CLASSIFIEDS[@]} + ${#SOCIAL[@]} + ${#OTHER[@]} ))

echo "============================================================"
echo "  TOTALE FONTI: $TOTAL"
echo "============================================================"
echo ""
echo "ISTRUZIONI:"
echo "1. Apri ogni link nel browser"
echo "2. Registrati se richiesto (usa email: $EMAIL)"
echo "3. Inserisci: Titolo='$TITLE', URL='$SITE'"
echo "4. Categoria: Incontri / Dating / Servizi Online"
echo "5. Descrizione: '$DESC'"
echo "6. Invia e passa al prossimo"
echo ""
echo "CONSIGLI:"
echo "- Inizia dalle TOP DIRECTORY (DA 60+) per massimo valore"
echo "- Poi fai le DIRECTORY ITALIANE (SEO locale)"
echo "- Poi SOCIAL BOOKMARKING (veloci)"
echo "- Lascia le altre per dopo"
echo ""
echo "Fai 5-10 al giorno per non sembrare spam"
echo "============================================================"