#!/bin/bash
# =============================================================
# BACKLINK SUBMISSION — Incontri di Bakeka
# =============================================================
# Apri i link seguenti e registra il sito su ogni directory.
# Alcune richiedono registrazione gratuita, altre sono dirette.
# =============================================================

SITE="https://incontridibakeka.com"
TITLE="Incontri di Bakeka"
DESC="Marketplace per incontri e amicizie in Italia. Profili verificati, connessioni reali. Annunci di incontri a Roma, Milano, Napoli e tutte le città italiane."
EMAIL="walterzannoni90@gmail.com"
CATEGORY="Incontri, Annunci, Dating"

echo "=================================="
echo "  BACKLINK SUBMISSION TOOL"
echo "  $TITLE"
echo "=================================="
echo ""

# Directory che accettano submission via web
echo "Apri questi link nel browser e compila i form:"
echo ""

declare -A DIRS
# Directory italiane
DIRS["Elinko.it"]="https://www.elinko.it/inserisci-sito/"
DIRS["MrLink.it"]="https://www.mrlink.it/contatti/"
DIRS["Hotfrog.it"]="https://www.hotfrog.it/aggiungere-azienda"
DIRS["NuovoSito.com"]="https://www.nuovosito.com/inserisci-sito.asp"
DIRS["FreeOnline.org"]="https://www.freeonline.org/submit.php"
DIRS["Gratis.it"]="https://www.gratis.it/aj/aggiungi.php"
DIRS["Segnala.it"]="https://www.segnala.it/aggiungi-sito/"
DIRS["Aziende-Italiane"]="https://www.aziende-italiane-siti.it/inserisci-sito/"
DIRS["PagineBianche"]="https://www.paginebianche.it/inserisci-attivita"
DIRS["Tuttitalia"]="https://www.tuttitalia.it/segnala-sito/"
DIRS["InItalia"]="https://www.initalia.it/inserisci-sito/"
DIRS["SitiWebItalia"]="https://www.sitiwebitalia.net/aggiungi-sito/"
DIRS["WebItalia"]="https://www.webitalia.net/segnala/"
DIRS["ItaliaIndice"]="https://www.italiaindice.it/inserisci-sito/"
DIRS["Segnalo.it"]="https://www.segnalo.it/aggiungi-sito/"
DIRS["PagineGialle"]="https://www.paginegialle.it/inserisci-scheda"
DIRS["VirgilioSiti"]="https://siti.virgilio.it/aggiungi-sito.html"
DIRS["Katalogi.it"]="https://www.katalogi.it/aggiungi.php"
DIRS["TopDir.it"]="https://www.topdir.it/inserisci-sito/"
DIRS["Prontoweb.it"]="https://www.prontoweb.it/aggiungi-sito"
DIRS["SitiWeb24"]="https://www.sitiweb24.it/inserisci-sito/"
DIRS["PagineSiti"]="https://www.paginesiti.it/aggiungi-sito"
DIRS["MondoWeb"]="https://www.mondo-web.it/aggiungi-sito/"
DIRS["DirItalia"]="https://www.diritalia.it/inserisci/"
DIRS["AnnunciSubito"]="https://www.annunci-subito.it/inserisci-annuncio/"
DIRS["SitiAmici"]="https://www.sitiamici.net/aggiungi-sito/"
DIRS["ItalianDir"]="https://www.italiandir.it/submit.php"
DIRS["InRete"]="https://www.inrete.it/inserisci-sito/"
DIRS["Segnalazioni"]="https://www.segnalazioni.com/aggiungi-sito/"
# Directory internazionali
DIRS["DMOZ"]="https://dmoztools.net/submit/"
DIRS["YahooDirectory"]="https://directory.yahoo.com/"
DIRS["GoogleBusiness"]="https://www.google.com/business/go/"

for name in "${!DIRS[@]}"; do
  echo "  ➤ $name"
  echo "    ${DIRS[$name]}"
  echo ""
done

echo "=================================="
echo "  PROFILI SOCIAL DA CREARE"
echo "=================================="
echo "  ➤ Instagram: https://instagram.com"
echo "    Usa email: $EMAIL"
echo "    Nome profilo: incontri_di_bakeka"
echo "    Bio: Marketplace incontri Italia | Profili verificati"
echo "    Link in bio: $SITE"
echo "    → Posta 1 foto/giorno con hashtag: #incontri #Roma #Milano #dating #incontridibakeka"
echo ""
echo "  ➤ TikTok: https://tiktok.com"
echo "    Usa email: $EMAIL"
echo "    Nome profilo: incontridibakeka"
echo "    Bio: Il marketplace per incontri piu affidabile d'Italia"
echo "    Link in bio: $SITE"
echo "    → Video brevi (15-30s) con hashtag locali"
echo ""
echo "  ➤ Facebook: https://facebook.com"
echo "    Crea pagina: Incontri di Bakeka"
echo "    Categoria: Incontri/Amicizie"
echo "    Link: $SITE"
echo "    → Iscriviti a gruppi di annunci e commenta con link"
echo ""
echo "  ➤ Twitter/X: https://x.com"
echo "    Handle: @IncontriBakeka"
echo "    Bio: Annunci incontri Italia | Profili verificati"
echo "    Link: $SITE"
echo "    → Tweeta ogni giorno citando città italiane"
echo ""
echo "  ➤ LinkedIn: https://linkedin.com"
echo "    Crea pagina aziendale: Incontri di Bakeka"
echo "    Categoria: Servizi online"
echo "    Link: $SITE"
echo ""
echo "  ➤ Pinterest: https://pinterest.it"
echo "    Crea board: Incontri in Italia, Dating tips"
echo "    Pin con link al sito e ai blog post"
echo "    Link profilo: $SITE"
echo ""
echo "  ➤ YouTube: https://youtube.com"
echo "    Canale: Incontri di Bakeka"
echo "    Video: consigli per incontri, tour città italiane"
echo "    Descrizione + commenti con link: $SITE"
echo ""
echo "  ➤ Reddit: https://reddit.com"
echo "    Subreddit: r/Italia, r/ItalianDating, r/incontri"
echo "    Partecipa alle discussioni e lascia link quando pertinente"
echo ""
echo "  ➤ Telegram: https://t.me"
echo "    Crea canale: Incontri di Bakeka"
echo "    Pubblica annunci e link al sito"
echo "    Invita utenti dai gruppi di incontri"
echo ""

echo "=================================="
echo "  GOOGLE SEARCH CONSOLE"
echo "=================================="
echo "  1. Vai a: https://search.google.com/search-console"
echo "  2. Accedi con l'account Google dell'azienda"
echo "  3. Aggiungi proprieta: $SITE"
echo "  4. Verifica: DNS (aggiungi record TXT) o file HTML"
echo "  5. Invia sitemap: $SITE/sitemap.xml"
echo ""

echo "=================================="
echo "  GOOGLE BUSINESS PROFILE"
echo "=================================="
echo "  1. Vai a: https://business.google.com/"
echo "  2. Crea profilo con nome attivita: Incontri di Bakeka"
echo "  3. Categoria: Sito di incontri / Servizi online"
echo "  4. Aggiungi sito web: $SITE"
echo ""

echo "=================================="
echo "  ALTRE STRATEGIE"
echo "=================================="
echo "  ➤ Forum Italiani (crea profilo con firma link):"
echo "    - https://forumfree.net"
echo "    - https://forumcommunity.net"
echo "    - https://forum.tuttoandroid.net"
echo "    - https://forum.html.it"
echo "    - https://forum.pcfaster.it"
echo "    - https://forum.incontri.forumfree.it"
echo "    - https://forum.donna.it"
echo ""
echo "  ➤ Siti di annunci gratuiti (pubblica link):"
echo "    - https://www.subito.it (inserisci annuncio servizi)"
echo "    - https://www.bakeka.it (annunci incontri)"
echo "    - https://www.annunci69.it"
echo "    - https://www.incontritop.it"
echo "    - https://www.anunciositalia.com"
echo ""
echo "  ➤ Social bookmarking:"
echo "    - https://segnalo.it"
echo "    - https://www.diggitalia.it"
echo "    - https://www.bookmarky.it"
echo "    - https://www.segnala.org"
echo ""
echo "  ➤ Commenti blog:"
echo "    - Cerca 'incontri blog Italia' su Google"
echo "    - Cerca 'dating Italia blog' su Google"
echo "    - Lascia commenti pertinenti con link al sito"
echo ""
echo "  ➤ Guest Post:"
echo "    - Contatta blog di settore (dating, incontri, lifestyle)"
echo "    - Offri articoli tipo 'Guida agli incontri a [città]'"
echo ""
echo "  ➤ Google Maps / Places:"
echo "    - Aggiungi il sito come 'Servizio online' su Google Maps"
echo "    - Link: https://www.google.com/business/go/"
echo ""
echo "  ➤ WhatsApp / Telegram:"
echo "    - Crea gruppo Telegram 'Annunci Incontri Italia'"
echo "    - Condividi link del sito nel gruppo"
echo "    - Inserisci link in stato WhatsApp"
echo ""
echo "  ➤ Medium / LinkedIn Articles:"
echo "    - Scrivi articolo su Medium: https://medium.com"
echo "    - Esempio: 'Come trovare incontri sicuri in Italia'"
echo "    - Link al sito e ai blog post"
echo ""
echo "  ➤ Question & Answer:"
echo "    - https://www.quora.com (cerca domande su incontri)"
echo "    - https://answers.yahoo.com"
echo "    - https://www.supermoney.it (domande finanza/dating)"
echo "    - Rispondi e includi link al sito"
echo ""
echo "  ➤ Plugin commenti:"
echo "    - Usa Disqus o altri sistemi di commento"
echo "    - Commenta su blog popolari con link in firma"
echo ""
echo "  ➤ Fiverr / Freelance:"
echo "    - Offri servizio 'Promozione sito web' low cost"
echo "    - In cambio, chiedi backlink da siti esistenti"
echo ""
echo "=================================="
echo "  CONTENUTI AIUTANO LA CRESCITA"
echo "=================================="
echo "  ➤ Genera 1 blog post a settimana (AI-assisted)"
echo "    - Targeting: 'incontri [città]' keyword"
echo "    - Nuove città non ancora coperte"
echo ""
echo "  ➤ Crea pagina 'Annunci [città]' per ogni città"
echo "    - Testo ottimizzato SEO, link a pagina categoria"
echo ""
echo "  ➤ Crea pagina 'Come funziona' guida dettagliata"
echo ""
echo "=================================="
echo "  AUTOMAZIONE"
echo "=================================="
echo "  ➤ Usa strumenti come:"
echo "    - https://www.screamingfrog.co.uk/seo-spider/ (audit SEO gratuito)"
echo "    - https://search.google.com/search-console/about (monitora indicizzazione)"
echo "    - Google Analytics (traffico e fonti)"
echo "    - https://ahrefs.com (prova gratuita backlink analysis)"
echo ""
echo "FATTO! Buona indicizzazione! 🚀"
